apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nominatim.fullname" . }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nominatim.selectorLabels" . | nindent 6 }}

  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nominatim.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nominatim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          workingDir: {{ .Values.nominatim.projectDir }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.nominatim.extraEnv }}
            {{- include "common.tplvalues.render" (dict "value" .Values.nominatim.extraEnv "context" $) | nindent 12 }}
            {{- end }}
            - name: NOMINATIM_DATABASE_DSN
              value: {{ include "nominatim.databaseUrl" . }}
            - name: NOMINATIM_DATABASE_MODULE_PATH
              value: {{ .Values.nominatim.databaseModulePath }}
            - name: NOMINATIM_REPLICATION_URL
              value: {{ .Values.nominatimReplications.replicationUrl }}
          command:
            - /bin/bash
            - -ec
            - |
                cd ${PROJECT_DIR} && nominatim refresh --website
                /usr/sbin/apache2ctl -D FOREGROUND
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
              {{- if .Values.flatnodes.enabled }}
            - mountPath: /nominatim/flatnode
              name: nominatim
              subPath: flatnode
              {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if  .Values.flatnodes.enabled }}
        - name: nominatim
          persistentVolumeClaim:
            claimName: {{ .Values.flatnodes.existingClaim | default (include "nominatim.fullname" .) }}
        {{- end }}
        - name: dshm
          emptyDir:
            medium: Memory