apiVersion: v1
kind: Secret
metadata:
  name: {{ template "futtertrog.fullname" . }}
type: Opaque
data:
  {{- if .Values.appKey }}
  APP_KEY: {{ .Values.appKey | b64enc }}
  {{- else }}
  APP_KEY: {{ randAlphaNum 10 | b64enc  | quote }}
  {{- end }}

  DB_PASSWORD: {{ .Values.mariadb.db.password | b64enc }}

  {{- if .Values.holzkeLogin }}
  HOLZKE_LOGIN: {{ .Values.holzkeLogin | quote | b64enc }}
  {{- end }}

  {{- if .Values.holzkePassword }}
  HOLZKE_PASSWORD: {{ .Values.holzkePassword | b64enc }}
  {{- end }}

  {{- if .Values.nexmoSecret}}
  NEXMO_SECRET: {{ .Values.nexmoSecret | quote }}
  {{- end }}

  {{- if .Values.gitlabClientId}}
  GITLAB_CLIENT_SECRET: {{ .Values.gitlabClientSecret }}
  {{- end }}