{{- if and .Values.updates.enabled (not .Values.import.enabled) }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "openstreetmaps-tile-server.fullname" . }}-updates
  labels:
    app.kubernetes.io/name: {{ include "openstreetmaps-tile-server.name" . }}-updates
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}-updates
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              workingDir: /openstreetmaps-tile-server
              env:
                - name: OSM2PGSQL_EXTRA_ARGS
                  value: {{ include "openstreetmaps-tile-server.databaseDSN" . }}
              command:
                - openstreetmap-tiles-update-expire
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /var/lib/mod_tile
                  name: tiles
                  subPath: mod_tile
          restartPolicy: OnFailure
          volumes:
          - name: tiles
            {{- if  .Values.persistence.enabled }}
            persistentVolumeClaim:
              claimName: {{ .Values.persistence.existingClaim | default (include "openstreetmaps-tile-server.fullname" .) }}
            {{- else }}
            emptyDir: {}
            {{- end }}
          - name: dshm
            emptyDir:
              medium: Memory
{{- end }}
