{{- if and .Values.updates.enabled (not .Values.import.enabled) }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "openstreetmaps-tile-server.fullname" . }}-updates
  labels:
    app.kubernetes.io/name: {{ include "openstreetmaps-tile-server.name" . }}-updates
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - {{ include "openstreetmaps-tile-server.name" . }}
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: {{ .Chart.Name }}-updates
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              workingDir: /openstreetmaps-tile-server
              env:
                - name: DATABASE_DSN
                  value: {{ include "openstreetmaps-tile-server.databaseDSN" . }}
                - name: PGPASSWORD
                  value: {{ include "openstreetmaps-tile-server.databasePassword" . }}
              command:
                - /bin/bash
                - -ec
                - |
                    ln -s /dev/stdout /var/log/tiles/run.log
                    sed -i s+TRIM_OPTIONS=.*+TRIM_OPTIONS="\"-d gis --host tiles-postgresql --user postgres --password\""+g /usr/bin/openstreetmap-tiles-update-expire
                    sed -i s+DBNAME=.*+DBNAME=${DATABASE_DSN}+g /usr/bin/openstreetmap-tiles-update-expire

                    openstreetmap-tiles-update-expire
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /var/lib/mod_tile
                  name: tiles
                  subPath: mod_tile
          restartPolicy: OnFailure
          volumes:
          - name: tiles
            {{- if  .Values.persistence.enabled }}
            persistentVolumeClaim:
              claimName: {{ .Values.persistence.existingClaim | default (include "openstreetmaps-tile-server.fullname" .) }}
            {{- else }}
            emptyDir: {}
            {{- end }}
          - name: dshm
            emptyDir:
              medium: Memory
{{- end }}
