{{- if .Values.import.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-init
spec:
  template:
    spec:
      initContainers:
{{/*        - name: download-pbf*/}}
{{/*          image: curlimages/curl*/}}
{{/*          workingDir: /osm-tiles*/}}
{{/*          volumeMounts:*/}}
{{/*            - mountPath: /osm-tiles*/}}
{{/*              name: data*/}}
{{/*          command:*/}}
{{/*            - curl*/}}
{{/*            - -L*/}}
{{/*            - {{ .Values.import.pbfUrl }}*/}}
{{/*            - --create-dirs*/}}
{{/*            - -o*/}}
{{/*            - data.osm.pbf*/}}

        - name: build-openstreetmap-carto
          image: node:lts
          workingDir: /osm-tiles/
          volumeMounts:
            - mountPath: /osm-tiles
              name: data
          command:
            - /bin/bash
            - -ec
            - |
              wget -c https://github.com/gravitystorm/openstreetmap-carto/archive/refs/tags/v5.3.1.tar.gz -O - | tar -xz
              cd openstreetmap-carto-5.3.1
              sed -ie 's#https:\/\/naciscdn.org\/naturalearth\/110m\/cultural\/ne_110m_admin_0_boundary_lines_land.zip#https:\/\/naturalearth.s3.amazonaws.com\/110m_cultural\/ne_110m_admin_0_boundary_lines_land.zip#g' external-data.yml
              npm install -g carto
              carto project.mml > mapnik.xml

{{- if .Values.updates.enabled }}
        - name: initialize-updates
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          workingDir: /osm-tiles
          volumeMounts:
            - mountPath: /osm-tiles
              name: data
          command:
            - /bin/bash
            - -ec
            - |
              # determine and set osmosis_replication_timestamp (for consecutive updates)
              osmium fileinfo data.osm.pbf > /var/lib/mod_tile/data.osm.pbf.info
              osmium fileinfo data.osm.pbf | grep 'osmosis_replication_timestamp=' | cut -b35-44 > /var/lib/mod_tile/replication_timestamp.txt
              REPLICATION_TIMESTAMP=$(cat /var/lib/mod_tile/replication_timestamp.txt)

              # initial setup of osmosis workspace (for consecutive updates)
              openstreetmap-tiles-update-expire $REPLICATION_TIMESTAMP

        - name: download-poly
          image: curlimages/curl
          workingDir: /var/lib/mod_tile
          volumeMounts:
            - mountPath: /var/lib/mod_tile
              name: tiles
          command:
            - curl
            - -L
            - {{ .Values.updates.polyfUrl }}
            - --create-dirs
            - -o
            - data.poly
{{- end }}

{{/*        - name: osm2psql*/}}
{{/*          image: "robjuz/osm2pgsql"*/}}
{{/*          volumeMounts:*/}}
{{/*            - mountPath: /osm-tiles*/}}
{{/*              name: data*/}}
{{/*            - mountPath: /dev/shm*/}}
{{/*              name: dshm*/}}
{{/*          command:*/}}
{{/*            - /bin/bash*/}}
{{/*            - -ec*/}}
{{/*            - |*/}}
{{/*              osm2pgsql -d {{ include "osm-tiles.databaseDSN" . }} \*/}}
{{/*              --create -G --hstore \*/}}
{{/*              --tag-transform-script /osm-tiles/openstreetmap-carto-5.3.1/openstreetmap-carto.lua \*/}}
{{/*              --number-processes {{ .Values.import.threads | quote }} \*/}}
{{/*              -S /osm-tiles/openstreetmap-carto-5.3.1/openstreetmap-carto.style \*/}}
{{/*              /osm-tiles/data.osm.pbf*/}}

        - name: create-indexes
          image: "bitnami/postgresql"
          volumeMounts:
            - mountPath: /osm-tiles
              name: data
            - mountPath: /dev/shm
              name: dshm
          command:
            - psql
            - -d
            - {{ include "osm-tiles.databaseDSN" . }}
            - -f
            - /osm-tiles/openstreetmap-carto-5.3.1/indexes.sql

        - name: import-external-data
          image: python:3
          volumeMounts:
          - mountPath: /osm-tiles
            name: data
          command:
            - python3
            - /osm-tiles/openstreetmap-carto-5.3.1/scripts/get-external-data.py
            - -H {{ include "osm-tiles.databaseHost" .}}
            - -U postgres
            - -w tiles
            - -c /osm-tiles/openstreetmap-carto-5.3.1/external-data.yml
            - -D /osm-tiles/openstreetmap-carto-5.3.1/data

      containers:
        - name: import
          image: python:3
          command:
            - touch /var/lib/mod_tile/planet-import-complete
          volumeMounts:
            - mountPath: /var/lib/mod_tile
              name: tiles
              subPath: mod_tile
      restartPolicy: OnFailure
      volumes:
        - name: tiles
        {{- if  .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "common.names.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data
          emptyDir: {}
{{- end }}