{{- if .Values.import.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "osm-tiles.fullname" . }}-init
spec:
  template:
    spec:
      initContainers:
        - name: download-pbf
          image: curlimages/curl
          workingDir: /osm-tiles
          volumeMounts:
            - mountPath: /osm-tiles
              name: data
          command:
            - curl
            - -L
            - {{ .Values.import.pbfUrl }}
            - --create-dirs
            - -o
            - data.osm.pbf
{{- if .Values.updates.enabled }}
        - name: initialize-updates
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          workingDir: /osm-tiles
          volumeMounts:
            - mountPath: /osm-tiles
              name: data
          command:
            - /bin/bash
            - -ec
            - |
              # determine and set osmosis_replication_timestamp (for consecutive updates)
              osmium fileinfo data.osm.pbf > /var/lib/mod_tile/data.osm.pbf.info
              osmium fileinfo data.osm.pbf | grep 'osmosis_replication_timestamp=' | cut -b35-44 > /var/lib/mod_tile/replication_timestamp.txt
              REPLICATION_TIMESTAMP=$(cat /var/lib/mod_tile/replication_timestamp.txt)

              # initial setup of osmosis workspace (for consecutive updates)
              openstreetmap-tiles-update-expire $REPLICATION_TIMESTAMP
        - name: download-poly
          image: curlimages/curl
          workingDir: /var/lib/mod_tile
          volumeMounts:
            - mountPath: /var/lib/mod_tile
              name: tiles
          command:
            - curl
            - -L
            - {{ .Values.updates.polyfUrl }}
            - --create-dirs
            - -o
            - data.poly
{{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.import.image.repository }}:{{ .Values.import.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_DSN
              value: {{ include "osm-tiles.databaseDSN" . }}
          command:
            - /bin/bash
            - -ec
            - |

              psql ${DATABASE_DSN} -c "CREATE EXTENSION IF NOT EXISTS postgis;"
              psql ${DATABASE_DSN} -c "CREATE EXTENSION IF NOT EXISTS hstore;"

              # Import data
              osm2pgsql -d ${DATABASE_DSN} --create --slim -G --hstore --tag-transform-script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua --number-processes ${THREADS} -S /home/renderer/src/openstreetmap-carto/openstreetmap-carto.style ./data.osm.pbf ${OSM2PGSQL_EXTRA_ARGS}

              # Create indexes
              psql ${DATABASE_DSN} -f /home/renderer/src/openstreetmap-carto/indexes.sql

              #Import external data
              python3 /home/renderer/src/openstreetmap-carto/scripts/get-external-data.py -H tiles-postgresql -U postgres -w tiles -c /home/renderer/src/openstreetmap-carto/external-data.yml -D /home/renderer/src/openstreetmap-carto/data

              # Register that data has changed for mod_tile caching purposes
              touch /var/lib/mod_tile/planet-import-complete
          volumeMounts:
            - mountPath: /osm-tiles
              name: data
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /var/lib/mod_tile
              name: tiles
              subPath: mod_tile
      restartPolicy: OnFailure
      volumes:
        - name: tiles
        {{- if  .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "osm-tiles.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data
          emptyDir: {}
{{- end }}