{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: {{ include "common.names.name" . }}
    app.kubernetes.io/name: {{ include "common.names.name" . }}-postgresql
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
      {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 2 }}
{{- end}}