apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: laravel-schedule-run
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      backoffLimit: 1
      template:
        spec:
          containers:
            - args:
                - /bin/bash
                - -c
                - php artisan schedule:run
              envFrom:
                - configMapRef:
                    name: {{ template "futtertrog.fullname" . }}
                - secretRef:
                    name: {{ template "futtertrog.fullname" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              name: artisan-schedule
              resources:
                limits:
                  cpu: 200m
                  memory: 200M
                requests:
                  cpu: 100m
                  memory: 100M
          restartPolicy: Never
  schedule: "* * * * *"
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 1