apiVersion: v2
name: kimai2
description: A Helm chart for Kubernetes
type: application
version: 3.0.0
appVersion: "apache-1.30.11-prod"

dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
